name: Coding Style

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.parallel }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress

      - name: Run Pint
        run: php vendor/bin/pint --test -v
