name: Static Analysis

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHPStan ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress
